govsso-enduserselfservice:
  session:
    max-idle-time: PT15m
    max-age: PT12h
  govsso-session:
    base-url: https://session.localhost:15443/
    tls:
      trust-store: classpath:enduserselfservice.localhost.session.truststore.p12
      trust-store-password: changeit

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include:
            - readinessState
            - ignite
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

server:
  port: 25443
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3
    key-store: classpath:enduserselfservice.localhost.keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    protocol: TLS
  servlet:
    session:
      cookie:
        name: __Host-SESSION
        same-site: lax

spring:
  application:
    name: govsso-enduserselfservice
  main:
    banner-mode: off

tara:
  client-id: govsso-enduserselfservice
  client-secret: secret
  issuer-uri: https://tara.localhost:16443
  redirect-uri: https://enduserselfservice.localhost:25443/login/oauth2/code/tara
  trust-store: classpath:enduserselfservice.localhost.tara.truststore.p12
  trust-store-password: changeit

ignite:
  ignite-instance-name: govsso-enduserselfservice-ignite
  metrics-log-frequency: 300000
  system-worker-blocked-timeout: 86400000
  failure-detection-timeout: 86400000
  client-failure-detection-timeout: 86400000
  discovery-spi:
    ip-finder:
      addresses:
        - 127.0.0.1
  ssl-context-factory:
    key-store-type: PKCS12
    key-store-file-path: src/main/resources/enduserselfservice.localhost.keystore.p12
    key-store-password: changeit
    trust-store-type: PKCS12
    trust-store-file-path: src/main/resources/enduserselfservice.localhost.ignite.truststore.p12
    trust-store-password: changeit
    protocol: TLSv1.3
    protocols:
      - TLSv1.3
    cipher-suites:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
